# Generated by Django 6.0.7 on 2026-10-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_campaign_event_delete_event'),
        ('tracking', '0007_alter_campaignrecipientstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_logs', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
